import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Siderbar";
import SupaBaseProviders from "@/providers/SupaBaseProviders";
import UserProvider from "@/providers/userProvider";
import ModalProvider from "@/providers/ModalProvider";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by ArsDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SupaBaseProviders>
          <UserProvider>
            <ModalProvider/>
              <Sidebar>{children}</Sidebar>
          </UserProvider>
        </SupaBaseProviders>
      </body>
    </html>
  );
}
